environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"

install:
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install --user -U pip
  - pip install --user pipenv
  - python -m pipenv install --dev
    #  - python -m pipenv run python -m pip install -e .
  - python bin/downloads.py
  - SET "PATH=C:\\MinGW\\bin;%PATH%"
  - mingw-get update

before_test:
  - python -m pipenv --version
  - python -m pipenv run python --version
  - python -m pipenv run scons --version

build: off

test_script:
  #  - python -m pipenv run python -m unittest discover -t . -s "test\\unit"
  - cmd: powershell -Command "& { python -m pipenv run python runtest --verbose=2 -e test\\system; if($LastExitCode -eq 2 -Or $LastExitCode -eq 0) { $host.SetShouldExit(0)} else {$host.SetShouldExit(1)}}"
