environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
      PYPATH: "%APPDATA%\\Python\\Scripts;%PYTHON%;%PYTHON%\\Scripts"
    - PYTHON: "C:\\Python35-x64"
      PYPATH: "%APPDATA%\\Python\\Python35\\Scripts;%PYTHON%;%PYTHON%\\Scripts"
    - PYTHON: "C:\\Python36-x64"
      PYPATH: "%APPDATA%\\Python\\Python36\\Scripts;%PYTHON%;%PYTHON%\\Scripts"
    - PYTHON: "C:\\Python37-x64"
      PYPATH: "%APPDATA%\\Python\\Python37\\Scripts;%PYTHON%;%PYTHON%\\Scripts"

install:
  - SET "PATH=%PYPATH%;%PATH%"
  - SET "TESTCOMMON_PASS_SKIPS=1"
  - python -m pip install -U pip
  - python -m pip install -U virtualenv
  - python -m pip install -U pipenv
  - python -m pipenv install --dev
  - python bin/downloads.py
  - SET "PATH=C:\\MinGW\\bin;%PATH%"
  - mingw-get update

before_test:
  - python -m pipenv --version
  - python -m pipenv run python --version
  - python -m pipenv run scons --version

build: off

matrix:
  allow_failures:
    - PYTHON: "C:\\Python27-x64"

test_script:
  - python -m pipenv run python runtest --verbose=2 -e "test\\system"
